version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "lib/build.gradle" }}s
      - run:
          name: Build
          command: ./gradlew build
       - save_cache:
         paths:
           - ~/.gradle
         key: jars-{{ checksum "lib/build.gradle" }}

  publish:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Publish
          command: ./gradlew clean build bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY -PdryRun=false

workflows:
  version: 2
  commit:
    jobs:
      - build
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master